name: Build
on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-2016]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Upgrade node-gyp
        if: runner.os == 'Windows'
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
        shell: powershell
      - name: Install Node Modules
        run: npm ci
      - name: Build Electron app
        run: npm run build
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          skip_build: true
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
